### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by 1j01** [dy/parenthesis#1]
> ``` js
> parenthesis.parse(':click :on( :not( :nth-child(5) ) )');
> 
> //result
> [ ':click :on\\3', '5', ' :nth-child\\1 ', ' :not\\2 ' ]
> ```

Wouldn't a better format be `[ ':click :on', [' :not', [' :nth-child', ['5'], ' '], ' '], ' ']`?

(I don't actually have a use case for this module, full disclosure)

**Comment by dy** [comment]
Seems reasonable, looks easier. Solves the problem of escaping `\\x` characters in an input string.
The only (possible) disadvantage - inability to make multiple insertions like

``` js
parenthesis.stringify(['#\\1\\1\\2\\2\\3\\3', '0', '1', '2' ]);
```

Though me neither have a use case for that.

**Comment by 1j01** [comment]
Alright then, if you want to do some refactoring and release a 2.0 of this, feel free to do so.

**Comment by dy** [comment]
XD Alrighty. It takes some pondering tho. Can’t think up anything easy off the bat.

**Comment by dy** [comment]
I’m afraid that according to the paradigm _users over authors over implementors over specifiers over theoretical purity_, the suggested format is less useful.

Imagine an example.
A source code:

``` c
var parts = parse('min (min (a, b), c)');
```

Parsed by the current implementation:

``` js
parts === ["min \2;", "a, b", "min \1, c"];
```

So we can easily do per-component processing, being sure that each component contains no parentheses, like so:

``` js
parts = parts.map(function (comp) { return process(comp) });
```

In case if we have parsed to suggested structure, processing becomes something non-trivial:

``` js
var parts = parse('min (min (a, b), c)');
//parts === ['min', [ 'min', [ 'a, b' ] ], 'c' ];
parts.map(function mapPart (part) {
  if (Array.isArray(part)) {
    return mapPart(part);
  } else {
    return process(part)
  }
});
```

Obviously following the logic of the processing becomes complicated, due to human mind works better with linear sequences (not every of course, just citing Alan Cooper). Not only now it is difficult to process, but to restructure things, like re-nesting, and merging things back as well.

So that solution seems theoretically perfectly pure, but in practice it is difficult to deal with.

So waiting for other use-cases, proving the other POV.

**Comment by dy** [comment]
After providing the brackets in the result, the POV slightly changed.

The point for is possibility to get rid of the need of stringify method:

``` js
['a(', ['b[', ['c'], ']'], ')'] + '' //⇒ a(b[c])
```

Quite concise.

Another point for is ability to analyse resulting structure the way easier. For example, if we need only parens containing no other parens, eg `a(b(c)) ⇒ b(c)`, with nested arrays it is flexible and possible as

``` js
['min(', ['min(', ['a, b'], ')' ], ', c)' ].reduce(function process (prev, curr) {
//a call
if (Array.isArray(curr)) {
  return curr.reduce(process, '');
}
//simple string
else {
  return min(getMethodName(prev) + curr);
}
}, '')
```

whereas with sequence of references we would deal with cross-checking by regexps.

**Comment by dy** [comment]
Well, actually stringification is not that easy, i was wrong.

**Comment by dy** [comment]
The abovementioned behavior is now default in @3.0.0.
The flat version is possible by passing `flat: true` into options.
